import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    'intro',
    'quick-start',
    {
      type: 'category',
      label: 'Core Features',
      items: [
        'features/git-workflow',
        'features/editor-actions',
        'features/batch-review',
        'features/ai-chat',
        'features/advanced-features',
        'features/release-orchestrator',
        'features/continuous-feedback',
        'features/mcp',
        'features/rag',
      ],
    },
    {
      type: 'category',
      label: 'Customization',
      items: [
        'customization/prompts',
      ],
    },
    {
      type: 'category',
      label: 'AI Models',
      items: [
        'models/cloud-providers',
        'models/ollama',
        'models/openai-compatible',
      ],
    },
    {
      type: 'category',
      label: 'Integration',
      items: [
        'features/integrations',
        'features/ci-cd',
      ],
    },
    {
      type: 'category',
      label: 'Reference',
      items: [
        {
          type: 'autogenerated',
          dirName: 'reference',
        },
      ],
    },
  ],
};

export default sidebars;
