/**
 * F-010: CI/CD Integration — GitHub PR comment posting
 */

import axios from 'axios';

export interface PrContext {
  owner: string;
  repo: string;
  prNumber: number;
  token: string;
}

/** Parse PR context from environment variables set by GitHub Actions. */
export function getPrContextFromEnv(): PrContext | null {
  const token = process.env.GITHUB_TOKEN ?? '';
  const ref = process.env.GITHUB_REF ?? ''; // refs/pull/123/merge
  const repoFull = process.env.GITHUB_REPOSITORY ?? ''; // owner/repo

  if (!token || !repoFull) {
    return null;
  }

  const prMatch = ref.match(/refs\/pull\/(\d+)/);
  if (!prMatch) {
    return null;
  }

  const [owner, repo] = repoFull.split('/');
  const prNumber = parseInt(prMatch[1], 10);

  return { owner, repo, prNumber, token };
}

/** Parse PR context from a GitHub PR URL string. */
export function parsePrUrl(url: string, token: string): PrContext | null {
  const match = url.match(/github\.com\/([^/]+)\/([^/]+)\/pull\/(\d+)/);
  if (!match) {
    return null;
  }
  return {
    owner: match[1],
    repo: match[2],
    prNumber: parseInt(match[3], 10),
    token,
  };
}

/** Post a comment to a GitHub PR. Returns the comment URL. */
export async function postPrComment(
  ctx: PrContext,
  body: string,
): Promise<string> {
  const url = `https://api.github.com/repos/${ctx.owner}/${ctx.repo}/issues/${ctx.prNumber}/comments`;
  const response = await axios.post(
    url,
    { body },
    {
      headers: {
        Authorization: `token ${ctx.token}`,
        Accept: 'application/vnd.github.v3+json',
        'User-Agent': 'ollama-code-review-cli/1.0.0',
      },
      timeout: 30_000,
    },
  );
  return response.data?.html_url ?? url;
}

/** Format a review as a GitHub PR comment with badge summary. */
export function formatPrComment(
  reviewText: string,
  provider: string,
  model: string,
  profile: string,
  counts: { critical: number; high: number; medium: number; low: number },
): string {
  const score = Math.max(
    0,
    Math.min(100, 100 - counts.critical * 20 - counts.high * 10 - counts.medium * 5 - counts.low * 2),
  );
  const scoreEmoji = score >= 80 ? '🟢' : score >= 60 ? '🟡' : '🔴';

  return [
    `## 🤖 AI Code Review`,
    ``,
    `> **Provider:** ${provider} | **Model:** \`${model}\` | **Profile:** \`${profile}\``,
    `> **Score:** ${scoreEmoji} ${score}/100 &nbsp;|&nbsp; 🔴 ${counts.critical} critical &nbsp; 🟠 ${counts.high} high &nbsp; 🟡 ${counts.medium} medium &nbsp; 🔵 ${counts.low} low`,
    ``,
    `---`,
    ``,
    reviewText,
    ``,
    `---`,
    `<sub>Generated by [Ollama Code Review](https://github.com/glorynguyen/ollama-code-review)</sub>`,
  ].join('\n');
}
